swagger: "2.0"
info:
  description: "This is the API for Asset Store."
  version: "1.0.0"
  title: "Swagger for Asset Store API"
  contact:
    email: "Dhathri.Somavarapu@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8000"
basePath: "/api/v1/assets"
tags:
- name: "assets"
  description: "Everything about assets"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/dhathris/asset_store"
schemes:
- "http"
paths:
  /:
    post:
      tags:
      - "assets"
      summary: "Add one or more assets to the store"
      description: ""
      operationId: "addAssets"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "A list of assets to add"
        required: true
        schema:
            $ref: "#/definitions/Assets"
      responses:
        400:
          description: "Invalid input"
        201:
          description: "Created"
    get:
      tags:
      - "assets"
      summary: "Retrieve all assets in the store"
      description: ""
      operationId: "retriveAllAssets"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Assets"
  /{asset_name}:
    get:
      tags:
      - "asset"
      summary: "Retrieve an asset by name"
      description: "Returns a single asset"
      operationId: "getAssetByName"
      produces:
      - "application/json"
      parameters:
      - name: "asset_name"
        in: "path"
        description: "Name of the asset to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Asset"
        400:
          description: "Invalid name supplied"
        404:
          description: "Asset not found"

definitions:
  Asset:
    type: "object"
    required:
    - "asset_name"
    - "asset_type"
    - "asset_class"
    properties:
      asset_name:
        type: "string"
        description: "Alphanumeric ASCII, - and _ characters allowed in a string of length 4 to 64 characters"
        example: "Dove1"
      asset_type:
        type: "string"
        description: "Allowed values are (satellite, antenna)"
        enum:
        - "satellite"
        - "antenna"
        example: "satellite"
      asset_class:
        type: "string"
        description: "Allowed values for asset type satellite are (dove, skysat, rapideye), for asset type antenna are (dish, yagi)"
        enum:
        - "dove"
        - "skysat"
        - "rapideye"
        - "dish"
        - "yagi"
        example: "dove"
  Assets:
    type: "object"
    required:
    - "assets"
    properties:
      assets:
        type: "array"
        items:
          $ref: "#/definitions/Asset"
