# Generated by Django 2.1.4 on 2019-01-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=64)),
                ('asset_type', models.CharField(max_length=64)),
                ('asset_class', models.CharField(max_length=64)),
            ],
        ),
    ]
